EXECUTABLE=brickpartitioned
CPPFILES=$(EXECUTABLE).cpp
F90FILES=$(EXECUTABLE).F90
TARGETS=cppbuild f90build
#
# Use the following instead to build the MPI targets
#TARGETS=mpicppbuild mpif90build

include ../base.make
